spring:
#  mvc:
#    static-path-pattern: /static/**
#    servlet:
#      path: /api
#  h2:
#    console:
#      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    initialization-mode: always
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
