spring:
  batch:
    job:
      enabled: false
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    initialization-mode: always
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
  data:
    mongodb:
      host: localhost
      port: 27017
      database: libraryDB