spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: libraryDB
mongock:
  change-logs-scan-package:
    - ru.otus.library.changelog
  runner-type: InitializingBean
management:
  endpoints:
    web:
      exposure:
        include: health, metrics, logfile
  endpoint:
    health:
      show-details: always
  health:
    diskspace:
      enabled: true
    mongo:
      enabled: true
    custom:
      enabled: true
logging:
  file:
    path: logfile